# Generated by Django 3.1.3 on 2024-02-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240126_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='ユーザーネーム'),
        ),
    ]
